name: gitstuff
on:
  workflow_dispatch:
  push:
    branches: [main]
jobs:
  gitstuff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # get all history and tags
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.13.1" # The Go version to download (if necessary) and use.
      - run: |
          go get -u github.com/git-chglog/git-chglog/cmd/git-chglog
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Configure git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git config pull.ff only
          git tag --list
      # - name: Install commitizen
      #   run: |
      #     pip install commitizen
      # - name: Test commitizen bump
      #   run: |
      #     cz bump
      # - name: Test git-chglog
      #   run: |
      #     git-chglog --output CHANGELOG.md
      - run: echo "hello" > "hi.txt"
      - run: git commit -am "echo hello"
      - run: git status
      - run: git diff main origin/main
      - run: git log -- HEAD..origin/master
      - run: git fetch
      - run: git log -p HEAD..FETCH_HEAD
      - run: git pull # here is a change.


      # - name: Push changes
      #   run: |
      #     git pull
      #     git push --follow-tags --tags
